version: '2'
services:
  amule:
    image: hanghang/amule
    ports:
      - "4711:4711"
      - "4662:4662"
      - "4672:4672/udp"
    environment:
      - PUID=5000
      - GUID=5000
    networks:
      amule:
        aliases:
          - amule
    volumes:
      - /home/DataVolume/amuleworkingdir:/home/amule/.aMule
      - /home/DataVolume/amuleworkingdir/incoming:/incoming
      - /home/DataVolume/amuleworkingdir/Temp:/temp
networks:
  amule:
